/**
 * The one drift that has actually bitten this repo: `.github/workflows/daily.yml`
 * is generated by src/schedule.mjs, and an edit to either that forgets the other
 * silently forks them — the next `npm run schedule` then reverts a hand-hardened
 * workflow (see "Stop the scheduler template reverting the slug-push hardening").
 *
 * So: read the committed workflow, take the schedule out of its own cron line,
 * regenerate from the template, and require byte equality. Editing the workflow
 * now means editing the template and re-running the generator, which is the rule
 * the file's own header states.
 *
 * The launchd artifacts are not compared — they embed this machine's absolute
 * paths and are gitignored, so there is nothing committed to drift from. The
 * wrapper is instead pinned on the three properties a regression would silently
 * drop: the fast-forward-only pull, the skipped sync, and caffeinate.
 */

import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { workflow, wrapper } from './schedule.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

let passed = 0;
const failures = [];

function check(name, actual, expected) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) passed++;
  else failures.push(`${name}\n      got      ${a}\n      expected ${e}`);
}

// ------------------------------------------------------- the committed yml --
{
  const committed = readFileSync(join(ROOT, '.github', 'workflows', 'daily.yml'), 'utf8');
  const cron = /- cron: "(\d{1,2}) (\d{1,2}) \* \* \*"/.exec(committed);
  check('daily.yml: has a daily cron line', Boolean(cron), true);
  const [minute, hour] = [Number(cron?.[1]), Number(cron?.[2])];
  const generated = workflow({ hour, minute });
  check('daily.yml: is exactly what src/schedule.mjs generates', generated === committed, true);
  // On a mismatch the boolean above says nothing about where; point at the line.
  if (generated !== committed) {
    const a = committed.split('\n');
    const b = generated.split('\n');
    const at = a.findIndex((line, i) => line !== b[i]);
    failures.push(`  first divergence at daily.yml line ${at + 1}:\n      committed  ${a[at]}\n      generated  ${b[at]}`);
  }
}

// ------------------------------------------------------------- the wrapper --
{
  const sh = wrapper();
  check('wrapper: pulls fast-forward only', sh.includes('git pull --ff-only'), true);
  check('wrapper: skips the sync the workflow owns', sh.includes('--skip-sync'), true);
  check('wrapper: holds the machine awake for the run', sh.includes('/usr/bin/caffeinate -i -m -s'), true);
}

if (failures.length) {
  console.error(`\n${failures.length} failing:\n`);
  for (const f of failures) console.error(`  ✗ ${f}\n`);
  console.error(`${passed} passed, ${failures.length} failed`);
  process.exit(1);
}
console.log(`✓ ${passed} schedule checks passed`);
